packages:
  - apps/*
  - packages/*

allowBuilds:
  electron: true
  esbuild: true
  node-pty: true
  onnxruntime-node: true
  protobufjs: false
  sharp: false

supportedArchitectures:
  os:
    - current
    - linux
    - win32
  cpu:
    - x64
    - arm64
